@startuml

interface Base {
  _id: string
  createdAt: number
  createdBy: string
  updatedAt?: number
  updatedBy?: string
  deletedAt?: number
  deletedBy?: string
}

entity Movie<Base> {
  url: string
  title: string
  description?: string
  categories?: Category<ID>[]
  snapshots?: string[]
}

entity Category<Base> {
  name: string
}

entity Comment<Base>{
  movie: Movie<ID>
  parent: Comment<ID>
  text: string
}



@enduml